# Generated by Django 3.2.12 on 2022-03-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order_wishlist_payment_ordermapping_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
