# Generated by Django 4.0.2 on 2022-02-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcombinationimage_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombinationimage',
            name='product_combination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcombination'),
        ),
    ]
